# Generated by Django 5.2.7 on 2025-10-30 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('A', 'Ativo'), ('P', 'Pendente'), ('I', 'Inativo')], default='P', max_length=20),
        ),
    ]
