# Generated by Django 5.2.7 on 2025-10-30 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0003_add_colunas_dataPublicacaoEautor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('Ativo', 'Ativo'), ('Pendente', 'Pendente'), ('Inativo', 'Inativo')], default='Pendente', max_length=20),
        ),
    ]
