# Generated by Django 5.2.7 on 2025-10-30 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0004_mudando_valorDeStatus_aSerSalvo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Activity',
        ),
        migrations.DeleteModel(
            name='UserActivity',
        ),
    ]
