# Generated by Django 5.2.7 on 2025-10-31 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0005_remove_useractivity_activity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='description',
            new_name='descricao',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='title',
            new_name='titulo',
        ),
    ]
