# Generated by Django 5.2.7 on 2025-11-12 23:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationalPublication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Título da Publicação Educacional')),
                ('description', models.TextField(max_length=200, verbose_name='Descrição da Publicação Educacional')),
                ('link', models.URLField(blank=True, max_length=300, null=True, verbose_name='Link da Publicação Educacional')),
                ('embed_link', models.URLField(blank=True, max_length=300, null=True, verbose_name='Link de Incorporação da Publicação Educacional')),
                ('publication_date', models.DateTimeField(auto_now_add=True, verbose_name='Data de Publicação da Publicação Educacional')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='courses.course')),
            ],
        ),
    ]
