# Generated by Django 5.2.7 on 2025-11-14 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationalpublication',
            name='description',
            field=models.TextField(max_length=200, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='educationalpublication',
            name='embed_link',
            field=models.URLField(default='https://example.com', max_length=300, verbose_name='Link'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='educationalpublication',
            name='link',
            field=models.URLField(default='', max_length=300, verbose_name='Link'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='educationalpublication',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Título'),
        ),
    ]
