# Generated by Django 5.2.7 on 2025-11-14 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_alter_educationalpublication_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationalpublication',
            name='embed_link',
            field=models.URLField(blank=True, max_length=300, verbose_name='Link'),
        ),
    ]
