# Generated by Django 5.2.7 on 2025-11-15 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0003_alter_educationalpublication_embed_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationalpublication',
            name='embed_link',
            field=models.URLField(blank=True, max_length=300, null=True, verbose_name='Embed Link'),
        ),
    ]
