# Generated by Django 5.2.7 on 2025-10-21 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('educacao', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publicacaoeducacional',
            old_name='usuarioId',
            new_name='autor',
        ),
    ]
