# Generated by Django 5.2.7 on 2025-10-22 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educacao', '0002_vinculo_usuario_publicacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacaoeducacional',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
