# Generated by Django 5.2.7 on 2025-10-24 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educacao', '0003_publicacaoeducacional_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacaoeducacional',
            name='embed_link',
            field=models.URLField(blank=True, editable=False, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='publicacaoeducacional',
            name='link',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
