# Generated by Django 5.2.7 on 2025-10-30 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0005_remove_useractivity_activity_and_more'),
        ('educacao', '0004_add_coluna_embedlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacaoeducacional',
            name='curso',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='publicacoes', to='cursos.course'),
            preserve_default=False,
        ),
    ]
