# Generated by Django 5.2.7 on 2025-10-30 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0005_remove_useractivity_activity_and_more'),
        ('educacao', '0005_publicacaoeducacional_curso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacaoeducacional',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publicacoes', to='cursos.course'),
        ),
    ]
