# Generated by Django 5.2.7 on 2025-11-12 23:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título do Curso')),
                ('description', models.TextField(verbose_name='Descrição do Curso')),
                ('publication_date', models.DateField(auto_now_add=True, verbose_name='Data de publicação do Curso')),
                ('status', models.CharField(choices=[('Ativo', 'Ativo'), ('Pendente', 'Pendente'), ('Inativo', 'Inativo')], default='Pendente', max_length=20, verbose_name='Status do curso')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses_authored', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_date', models.DateTimeField(auto_now_add=True, verbose_name='Data da Matrícula do curso')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(related_name='courses_enrolled', through='courses.Enrollment', to=settings.AUTH_USER_MODEL),
        ),
    ]
