# Generated by Django 5.2.7 on 2025-11-14 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='course',
            name='publication_date',
            field=models.DateField(auto_now_add=True, verbose_name='Data de publicação'),
        ),
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('Ativo', 'Ativo'), ('Pendente', 'Pendente'), ('Inativo', 'Inativo')], default='Pendente', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Título'),
        ),
    ]
